# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       gobject-introspection

# >> macros
# << macros

Summary:    Introspection system for GObject-based libraries
Version:    1.32.0
Release:    1
Group:      Development/Libraries
License:    GPLv2+, LGPLv2+, MIT
URL:        http://live.gnome.org/GObjectIntrospection
Source0:    %{name}-%{version}.tar.xz
Source100:  gobject-introspection.yaml
Patch0:     0001-gir-gio-2.0.c-fix-wrong-naming.patch
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(libffi)
BuildRequires:  pkgconfig(libxml-2.0)
BuildRequires:  pkgconfig(xfixes)
BuildRequires:  pkgconfig(fontconfig)
BuildRequires:  pkgconfig(xft)
BuildRequires:  pkgconfig(freetype2)
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  pkgconfig(cairo)
BuildRequires:  pkgconfig(python-2.7)
BuildRequires:  pkgconfig(gtk-doc)
BuildRequires:  gettext
BuildRequires:  intltool
BuildRequires:  flex
BuildRequires:  bison
BuildRequires:  chrpath

%description
GObject Introspection can scan C header and source files in order to
generate introspection "typelib" files.  It also provides an API to examine
typelib files, useful for creating language bindings among other
things.


%package -n python-giscanner
Summary:    Python package for handling GObject introspection data
Group:      Development/Languages
Requires:   %{name} = %{version}-%{release}

%description -n python-giscanner
This package contains a Python package for handling the introspection
data from Python.


%package devel
Summary:    Libraries and headers for gobject-introspection
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   python-giscanner

%description devel
Libraries and headers for gobject-introspection.


%prep
%setup -q -n %{name}-%{version}

# 0001-gir-gio-2.0.c-fix-wrong-naming.patch
%patch0 -p1
# >> setup
# << setup

%build
# >> build pre
# Hack around broken ldd in x86_64
%if "%{_arch}" == "x86_64"
mkdir /tmp/bin
sed -e 's/lib64/lib/' /usr/bin/ldd > /tmp/bin/ldd
chmod a+x /tmp/bin/ldd
PATH=/tmp/bin:$PATH
%endif

(if ! test -x configure; then NOCONFIGURE=1 ./autogen.sh; fi;)
# << build pre

%configure --disable-static \
    --disable-gtk-doc

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
%doc COPYING
%{_libdir}/lib*.so.*
%dir %{_libdir}/girepository-1.0
%{_libdir}/girepository-1.0/*.typelib
# >> files
# << files

%files -n python-giscanner
%defattr(-,root,root,-)
%{_libdir}/gobject-introspection/giscanner
# >> files python-giscanner
# << files python-giscanner

%files devel
%defattr(-,root,root,-)
%{_libdir}/lib*.so
%{_libdir}/pkgconfig/*
%{_includedir}/*
%{_bindir}/g-ir-*
%{_datadir}/gir-1.0
%{_datadir}/aclocal/introspection.m4
%{_datadir}/gobject-introspection-1.0
%doc %{_mandir}/man1/*.gz
# >> files devel
# << files devel
